name: build CLI executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build executable with uv
        run: uv run pyinstaller --onefile --add-data ".env.example;." --name python-automation-cli cli/script_cli.py

      - name: Copy .env.example
        run: copy .env.example dist\.env.example

      - name: Zip the executable
        run: Compress-Archive -Path dist\* -DestinationPath python-automation-cli-windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-automation-cli-windows
          path: python-automation-cli-windows.zip
