name: release CLI executable

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv sync

      - name: Build executable with uv
        run: uv run pyinstaller --onefile --add-data ".env.example;." --name python-automation-cli cli/script_cli.py

      - name: Copy .env.example
        run: copy .env.example dist\.env.example

      - name: Zip the executable
        run: Compress-Archive -Path dist\* -DestinationPath python-automation-cli-windows.zip

      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: python-automation-cli-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
